-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 21:50:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema irs_news
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema irs_news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `irs_news` DEFAULT CHARACTER SET utf8 ;
USE `irs_news` ;

-- -----------------------------------------------------
-- Table `irs_news`.`news_`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irs_news`.`news_` ;

CREATE TABLE IF NOT EXISTS `irs_news`.`news_` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL,
  `abstract_` VARCHAR(155) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `date` DATE NOT NULL,
  `heat` INT(11) NOT NULL,
  `vector` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irs_news`.`coments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irs_news`.`coments` ;

CREATE TABLE IF NOT EXISTS `irs_news`.`coments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `content` VARCHAR(145) NOT NULL,
  `emotion` INT(11) NULL DEFAULT NULL,
  `news__id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_coment_news__idx` (`news__id` ASC),
  CONSTRAINT `fk_coment_news_`
    FOREIGN KEY (`news__id`)
    REFERENCES `irs_news`.`news_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irs_news`.`news_news_similar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irs_news`.`news_news_similar` ;

CREATE TABLE IF NOT EXISTS `irs_news`.`news_news_similar` (
  `news__id1` INT(11) NOT NULL,
  `news__id2` INT(11) NOT NULL,
  `similarity` DOUBLE NOT NULL,
  PRIMARY KEY (`news__id1`, `news__id2`),
  INDEX `fk_news_news_similar_news_2_idx` (`news__id2` ASC),
  CONSTRAINT `fk_news_news_similar_news_1`
    FOREIGN KEY (`news__id1`)
    REFERENCES `irs_news`.`news_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_news_similar_news_2`
    FOREIGN KEY (`news__id2`)
    REFERENCES `irs_news`.`news_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irs_news`.`vocabulary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irs_news`.`vocabulary` ;

CREATE TABLE IF NOT EXISTS `irs_news`.`vocabulary` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(45) NOT NULL,
  `idf` DOUBLE NOT NULL DEFAULT '0',
  `inverted_list` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irs_news`.`word_word_similar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irs_news`.`word_word_similar` ;

CREATE TABLE IF NOT EXISTS `irs_news`.`word_word_similar` (
  `vocabulary_id1` INT(11) NOT NULL,
  `vocabulary_id2` INT(11) NOT NULL,
  `similarity` DOUBLE NOT NULL,
  PRIMARY KEY (`vocabulary_id1`, `vocabulary_id2`),
  INDEX `fk_word_word_similar_vocabulary2_idx` (`vocabulary_id2` ASC),
  CONSTRAINT `fk_word_word_similar_vocabulary1`
    FOREIGN KEY (`vocabulary_id1`)
    REFERENCES `irs_news`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_word_word_similar_vocabulary2`
    FOREIGN KEY (`vocabulary_id2`)
    REFERENCES `irs_news`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `irs_news`.`word_word_synonymous`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irs_news`.`word_word_synonymous` ;

CREATE TABLE IF NOT EXISTS `irs_news`.`word_word_synonymous` (
  `vocabulary_id` INT(11) NOT NULL,
  `vocabulary_id1` INT(11) NOT NULL,
  `similarity` DOUBLE NOT NULL,
  PRIMARY KEY (`vocabulary_id`, `vocabulary_id1`),
  INDEX `fk_word_word_synonymous_vocabulary2_idx` (`vocabulary_id1` ASC),
  CONSTRAINT `fk_word_word_synonymous_vocabulary1`
    FOREIGN KEY (`vocabulary_id`)
    REFERENCES `irs_news`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_word_word_synonymous_vocabulary2`
    FOREIGN KEY (`vocabulary_id1`)
    REFERENCES `irs_news`.`vocabulary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
